### ISSUE TITLE
Remove filtered-out routes from shared detours

### ISSUE THREAD

**Issue by sherson** [umts/public-message-board#15]
In #4 I wrote:

> I don't think we need to remove filtered-out-routes if they share a detour with routes that we included in our URL parameter

I've changed my mind and now think we *should* remove filtered-out-routes from shared detours.

There is currently a detour for P20, P21, and P21E along with R29 (that basically doesn't affect UMass). Because it lists 4 routes, it's tall enough that it pushes the detour we care about mostly off the screen (in the iframe on both desktop and mobile). 

And even if it didn't push it off the screen, very few (if any) passengers at UMass even know those other routes exist... it's possible that some R29 passenger do, but even so it's probably still better to only show the UMass-area routes (to clean up the public messages list and reduce confusion for the other 99.9+% of our passengers).

I'm open to suggestions if anyone thinks otherwise.

**Comment by werebus** [comment]
> ...it's possible that some R29 passenger do...

I think that there's a pretty good likelihood that a given R29 knows about the other routes that travel in the same area as the R29. I also think excluding the other routes communicates that the detour _does_ affect the R29 but _does not_ affect any other routes.
