### ISSUE TITLE
Support HTML message rendering

### ISSUE THREAD

**Issue by benmelz** [umts/public-message-board#21]
Bustracker:
![b4b83499-bc74-485e-919f-77e17dca1c33](https://github.com/umts/public-message-board/assets/8195530/8cdcdeab-bb94-4663-aeb1-2ba5b0c68ded)

This app:
![Screenshot 2023-09-19 at 12 27 45 PM](https://github.com/umts/public-message-board/assets/8195530/c1ca9704-2224-4c93-9264-19a510fab91a)

Since Avail supports it, I guess we don't really have a choice either. Shouldn't be that bad, the two possible pain points I foresee are:
- picking a good sanitized rendering method
- getting that rendering method to play nice with react

**Comment by benmelz** [comment]
Quick research presents two options:
- [this react feature](https://react.dev/reference/react-dom/components/common#dangerously-setting-the-inner-html), which would require us to come up with our own sanitization process
- [this library](https://github.com/remarkablemark/html-react-parser), which seems to take care of everything, but should probably be vetted a bit

**Comment by werebus** [comment]
From the FAQ on `html-react-parser`:

> **Is this XSS safe?**
> 
> No, this library is not XSS (cross-site scripting) safe. See \#94.
>
> **Does invalid HTML get sanitized?**
> 
> No, this library does not sanitize HTML. See \#124, \#125, and \#141.
